2022-12-11 02:56:18,188 ERROR: Exception on /user/Test_user_1 [GET] [in C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\Coding\CS50x_Harvard\Final_Project\Blog\env\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "D:\Coding\CS50x_Harvard\Final_Project\Blog\app\routes.py", line 98, in user
    return render_template('user.html', user = user, posts = posts.items,
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\flask\templating.py", line 146, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "D:\Coding\CS50x_Harvard\Final_Project\Blog\env\lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "D:\Coding\CS50x_Harvard\Final_Project\Blog\env\lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "D:\Coding\CS50x_Harvard\Final_Project\Blog\env\lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "D:\Coding\CS50x_Harvard\Final_Project\Blog\env\lib\site-packages\jinja2\loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "D:\Coding\CS50x_Harvard\Final_Project\Blog\env\lib\site-packages\jinja2\environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "D:\Coding\CS50x_Harvard\Final_Project\Blog\env\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\Coding\CS50x_Harvard\Final_Project\Blog\app\templates\user.html", line 32, in template
    {{ form.submit(value = _('Unfollow', class_ = 'btn btn-default') }}
jinja2.exceptions.TemplateSyntaxError: unexpected '}', expected ')'
2022-12-11 02:56:40,295 ERROR: Exception on /user/Test_user_1 [GET] [in C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\Coding\CS50x_Harvard\Final_Project\Blog\env\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "D:\Coding\CS50x_Harvard\Final_Project\Blog\app\routes.py", line 98, in user
    return render_template('user.html', user = user, posts = posts.items,
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\flask\templating.py", line 146, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "D:\Coding\CS50x_Harvard\Final_Project\Blog\env\lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "D:\Coding\CS50x_Harvard\Final_Project\Blog\env\lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "D:\Coding\CS50x_Harvard\Final_Project\Blog\env\lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "D:\Coding\CS50x_Harvard\Final_Project\Blog\env\lib\site-packages\jinja2\loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "D:\Coding\CS50x_Harvard\Final_Project\Blog\env\lib\site-packages\jinja2\environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "D:\Coding\CS50x_Harvard\Final_Project\Blog\env\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\Coding\CS50x_Harvard\Final_Project\Blog\app\templates\user.html", line 32, in template
    {{ form.submit(value = _('Unfollow', class_ = 'btn btn-default') }}
jinja2.exceptions.TemplateSyntaxError: unexpected '}', expected ')'
2022-12-11 03:05:50,238 INFO: Blog startup [in D:\Coding\CS50x_Harvard\Final_Project\Blog\app\__init__.py:51]
2022-12-11 18:01:32,237 INFO: Blog startup [in D:\Coding\CS50x_Harvard\Final_Project\Blog\app\__init__.py:51]
2022-12-11 18:03:26,004 INFO: Blog startup [in D:\Coding\CS50x_Harvard\Final_Project\Blog\app\__init__.py:51]
2022-12-12 00:20:32,464 INFO: Blog startup [in D:\Coding\CS50x_Harvard\Final_Project\Blog\app\__init__.py:51]
2022-12-12 00:20:42,876 INFO: Blog startup [in D:\Coding\CS50x_Harvard\Final_Project\Blog\app\__init__.py:51]
2022-12-12 00:23:09,047 INFO: Blog startup [in D:\Coding\CS50x_Harvard\Final_Project\Blog\app\__init__.py:51]
2022-12-12 00:26:02,766 ERROR: Exception on /user/Test_user_2 [GET] [in C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\Coding\CS50x_Harvard\Final_Project\Blog\env\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "D:\Coding\CS50x_Harvard\Final_Project\Blog\app\routes.py", line 103, in user
    return render_template('user.html', user = user, posts = posts.items,
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\flask\templating.py", line 130, in _render
    rv = template.render(context)
  File "D:\Coding\CS50x_Harvard\Final_Project\Blog\env\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "D:\Coding\CS50x_Harvard\Final_Project\Blog\env\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\Coding\CS50x_Harvard\Final_Project\Blog\app\templates\user.html", line 1, in top-level template code
    {% extends "_layout.html" %}
  File "D:\Coding\CS50x_Harvard\Final_Project\Blog\app\templates\_layout.html", line 1, in top-level template code
    {% extends "bootstrap/base.html" %}
  File "D:\Coding\CS50x_Harvard\Final_Project\Blog\env\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "D:\Coding\CS50x_Harvard\Final_Project\Blog\env\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block 'doc'
    {%- block html %}
  File "D:\Coding\CS50x_Harvard\Final_Project\Blog\env\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block 'html'
    {% block body -%}
  File "D:\Coding\CS50x_Harvard\Final_Project\Blog\env\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block 'body'
    {% block content -%}
  File "D:\Coding\CS50x_Harvard\Final_Project\Blog\app\templates\_layout.html", line 47, in block 'content'
    {% block app_content %}
  File "D:\Coding\CS50x_Harvard\Final_Project\Blog\app\templates\user.html", line 26, in block 'app_content'
    {{ form.hidden_tag() }}
  File "D:\Coding\CS50x_Harvard\Final_Project\Blog\env\lib\site-packages\jinja2\environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
